language: node_js
node_js:
  - "4"

services:
  - redis-server

cache:
  directories:
    - node_modules

before_script:
  - npm run sass
  - NODE_ENV='ci' npm start&

script:
  - npm run test:ci
  - npm run test:acceptance