version: '3'
services:
  app:
    container_name: evw-self-serve
    build: 
      context: .
      args:
        NPM_AUTH_TOKEN: ${NPM_AUTH_TOKEN}
        NPM_AUTH_USERNAME: ${NPM_AUTH_USERNAME}
    environment:
    - NODE_ENV=docker-compose
    - MONGO_CONNECTION_STRING=mongodb://db:27017/evw-self-serve
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - /public
  db:
    image: mongo:3.2
    ports:
      - "27017:27017"
