version: '2'
services:
  app:
    build: .
    environment:
    - NODE_ENV=docker-compose
    - MONGO_CONNECTION_STRING=mongodb://db:27017/evw-self-serve
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
  db:
    image: mongo:3.2
    ports:
      - "27017:27017"
